services:
  gateway:
    image: bwdesigngroup/ignition-docker:8.1.44
    environment:
      GATEWAY_MODULES_ENABLED: perspective
      DEVELOPER_MODE: "Y"
    volumes:
      - ../build/Browser-Resource-Example.modl:/usr/local/bin/ignition/user-lib/modules/Browser-Resource-Example.modl
      - ./backups/gateway.gwbk:/restore.gwbk
      - ./temp:/workdir
    labels:
      traefik.enable: "true"
      traefik.hostname: "browser-resource"
    command: >
      -n browser-resource
      -r /restore.gwbk
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
